Ikoria Display:
  article_id: 410989
  cost_basis: 88.944
  stock: 5
  language: English
  purchase_date: 10.07.2020

Jumpstart Display:
  article_id: 441393
  cost_basis: 90.6745
  stock: 11
  language: English
  purchase_date: 26.06.2020

Throne of Eldraine Display:
  article_id: 389647
  cost_basis: 91.22
  stock: 4
  language: English
  purchase_date: 10.07.2020

Double Masters VIP Edition Booster:
  article_id: 482384
  cost_basis: 90.73
  stock: 10
  language: English
  purchase_date: 22.07.2020